[PHP]
; Memoire maximale qu'un script PHP peut utiliser
memory_limit = 256M

; Taille maximale des fichiers uploades
upload_max_filesize = 50M
post_max_size = 50M

; Temps max d'execution d'un script (en secondes)
max_execution_time = 120

; Afficher les erreurs en developpement (on desactivera en prod)
display_errors = Off
log_errors = On
error_log = /var/www/storage/logs/php_errors.log

; Timezone
date.timezone = Europe/Paris
